name: Deploy

on:
  push:
    branches: [ 2.1/release ]
  pull_request:
    branches: [ 2.1/release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: |
          chmod +x ./build/npm-install.sh
          ./build/npm-install.sh
        shell: bash

      - name: Deploy
        run: |
          npm run deploy
          npm run deploy:pages
          node ./node_modules/coveralls/bin/coveralls.js < ./reports/lcov.info
