name: Deploy

on:
  push:
    branches: [ 2.1/release ]
  pull_request:
    branches: [ 2.1/release ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: |
          chmod +x ./build/npm-install.sh
          ./build/npm-install.sh
        shell: bash

      - name: Deploy
        run: |
          npm run deploy
          npm run deploy:pages

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./reports/lcov.info"
